baseURL = "https://harper.blog/"
publishDir = "public"
languageCode = "en-us"
title = "Harper Reed's Blog"
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo = true
timeout = "300s"                 # Increased for large image processing
defaultContentLanguage = "en"
author = "Harper Reed"
disableKinds = []
timeZone = "America/Chicago"


[services.rss]
limit = 20 # Limits the number of items in RSS feed to prevent excessive bandwidth usage

[pagination]
pagerSize = "6"

[minify]
disableXML = true
# minifyOutput = true
