baseURL = "https://harper.blog/"
publishDir = "public"
languageCode = "en-us"
title = "Harper Reed's Blog"
canonifyURLs = true
enableRobotsTXT = true
paginate = 5

defaultContentLanguage = "en"
author = "Harper Reed"
disableKinds = [  ]
timeZone = "America/Chicago"
