[en]
title = "Harper Reed's Blog"
languageName = "English ğŸ‡ºğŸ‡¸"
languageCode = "en-US"
contentDir = "content"
weight = 1

[en.params]
description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
subtitle = "Musing from a normal person doing normal things"

[ja]
title = "ãƒãƒ¼ãƒ‘ãƒ¼ãƒ»ãƒªãƒ¼ãƒ‰ã®ãƒ–ãƒ­ã‚°"
languageName = "æ—¥æœ¬èª ğŸ‡¯ğŸ‡µ"
languageCode = "ja"
weight = 2

[ja.params]
description = "Harper Reedã«ã‚ˆã‚‹ã„ãã¤ã‹ã®æ–‡ç« ã€‚ä¸»ã«ãƒ†ã‚¯ãƒãƒ­ã‚¸ãƒ¼ã€æ”¿æ²»ã€ãã®ä»–ã®ã“ã¨ã«ã¤ã„ã¦"
subtitle = "æ™®é€šã®äººãŒæ™®é€šã®ã“ã¨ã‚’è€ƒãˆã‚‹éšæƒ³"

[es]
title = "Blog de Harper Reed"
languageName = "EspaÃ±ol ğŸ‡ªğŸ‡¸"
languageCode = "es"
weight = 3

[es.params]
description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
subtitle = "Musing from a normal person doing normal things"


# [ko]
# title = "í•˜í¼ ë¦¬ë“œì˜ ë¸”ë¡œê·¸"
# languageName = "í•œêµ­ì–´ ğŸ‡°ğŸ‡·"
# languageCode = "ko"
# weight = 4

# [ko.params]
# description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
# subtitle = "Musing from a normal person doing normal things"


# # [zh]
# title = "å“ˆç€Â·é›·å¾·çš„åšå®¢"
# languageName = "ä¸­æ–‡ ğŸ‡¨ğŸ‡³"
# languageCode = "zh-CN"
# weight = 5

# [zh.params]
# description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
# subtitle = "Musing from a normal person doing normal things"
