[en]
title = "Harper Reed's Blog"
languageName = "English ğŸ‡ºğŸ‡¸"
languageCode = "en-US"
contentDir = "content"
weight = 1

[en.params]
description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
subtitle = "Musing from a normal person doing normal things"

# [es]
# title = "Blog de Harper Reed"
# languageName = "EspaÃ±ol ğŸ‡ªğŸ‡¸"
# languageCode = "es"
# contentDir = "content.es"
# weight = 3

# [ja]
# title = "ãƒãƒ¼ãƒ‘ãƒ¼ãƒªãƒ¼ãƒ‰ã®ãƒ–ãƒ­ã‚°"
# languageName = "æ—¥æœ¬èª ğŸ‡¯ğŸ‡µ"
# languageCode = "ja"
# contentDir = "content.ja"
# weight = 2

# [ko]
# title = "í•˜í¼ ë¦¬ë“œì˜ ë¸”ë¡œê·¸"
# languageName = "í•œêµ­ì–´ ğŸ‡°ğŸ‡·"
# languageCode = "ko"
# contentDir = "content.ko"
# weight = 4

# # [zh]
# title = "å“ˆç€Â·é›·å¾·çš„åšå®¢"
# languageName = "ä¸­æ–‡ ğŸ‡¨ğŸ‡³"
# languageCode = "zh-CN"
# contentDir = "content.zh"
# weight = 5
