[en]
title = "Harper Reed's Blog"
languageName = "English ğŸ‡ºğŸ‡¸"
languageCode = "en-US"
contentDir = "content"
weight = 1

[en.params]
description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
subtitle = "Musing from a normal person doing normal things"

[ja]
title = "ãƒãƒ¼ãƒ‘ãƒ¼ãƒ»ãƒªãƒ¼ãƒ‰ã®ãƒ–ãƒ­ã‚°"
languageName = "æ—¥æœ¬èª ğŸ‡¯ğŸ‡µ"
languageCode = "ja"
weight = 2

[ja.params]
description = "Harper Reedã«ã‚ˆã‚‹ã„ãã¤ã‹ã®æ–‡ç« ã€‚ä¸»ã«ãƒ†ã‚¯ãƒãƒ­ã‚¸ãƒ¼ã€æ”¿æ²»ã€ãã®ä»–ã®ã“ã¨ã«ã¤ã„ã¦"
subtitle = "æ™®é€šã®äººãŒæ™®é€šã®ã“ã¨ã‚’è€ƒãˆã‚‹éšæƒ³"

[es]
title = "Blog de Harper Reed"
languageName = "EspaÃ±ol ğŸ‡ªğŸ‡¸"
languageCode = "es"
weight = 3

[es.params]
description = "Algunos escritos de Harper Reed. Principalmente sobre tecnologÃ­a, polÃ­tica y otras cosas"
subtitle = "Reflexiones de una persona normal haciendo cosas normales"


[ko]
title = "í•˜í¼ ë¦¬ë“œì˜ ë¸”ë¡œê·¸"
languageName = "í•œêµ­ì–´ ğŸ‡°ğŸ‡·"
languageCode = "ko"
weight = 4

[ko.params]
description = "í•˜í¼ ë¦¬ë“œê°€ ì“´ ê¸€ë“¤. ì£¼ë¡œ ê¸°ìˆ , ì •ì¹˜, ê·¸ë¦¬ê³  ë‹¤ì–‘í•œ ê²ƒë“¤ì— ëŒ€í•´ ì”ë‹ˆë‹¤"
subtitle = "í‰ë²”í•œ ì‚¬ëŒì´ í‰ë²”í•œ ì¼ì„ í•˜ë©° ë‚¨ê¸°ëŠ” ìƒê°ë“¤"

[zh]
title = "å“ˆç€Â·é›·å¾·çš„åšå®¢"
languageName = "ä¸­æ–‡ ğŸ‡¨ğŸ‡³"
languageCode = "zh-CN"
weight = 5

[zh.params]
description = "Harper Reedå†™çš„ä¸€äº›æ–‡ç« ã€‚ä¸»è¦å…³äºæŠ€æœ¯ã€æ”¿æ²»å’Œå…¶ä»–äº‹æƒ…"
subtitle = "ä¸€ä¸ªæ™®é€šäººåšæ™®é€šäº‹æƒ…æ—¶çš„æ€è€ƒ"

[it]
title = "Harper Reed's Blog"
languageName = "Italiano ğŸ‡®ğŸ‡¹"
languageCode = "it"
contentDir = "content"
weight = 7

[it.params]
description = "Alcuni scritti di Harper Reed. Principalmente su tecnologia, politica e altre cose"
subtitle = "Riflessioni di una persona normale che fa cose normali"

[fr]
title = "Blog de Harper Reed"
languageName = "FranÃ§ais ğŸ‡«ğŸ‡·"
languageCode = "fr"
contentDir = "content"
weight = 8

[fr.params]
description = "Des Ã©crits de Harper Reed. Principalement sur la technologie, la politique et d'autres choses"
subtitle = "RÃ©flexions d'une personne normale qui fait des choses normales"

[de]
title = "Harper Reed's Blog"
languageName = "Deutsch ğŸ‡©ğŸ‡ª"
languageCode = "de"
contentDir = "content"
weight = 9

[de.params]
description = "Einige Schriften von Harper Reed. HauptsÃ¤chlich Ã¼ber Technologie, Politik und andere Dinge"
subtitle = "Denkungen einer normalen Person, die normaler Dinge macht"

[id]
title = "Harper Reed's Blog"
languageName = "Indonesia ğŸ‡®ğŸ‡©"
languageCode = "id"
contentDir = "content"
weight = 10

[id.params]
description = "Beberapa tulisan dari Harper Reed. Utama tentang teknologi, politik, dan hal lainnya"
subtitle = "Pikiran dari seorang orang biasa yang melakukan hal-hal biasa"

[hi]
title = "à¤¹à¤¾à¤°à¥à¤ªà¤° à¤°à¥€à¤¡ à¤•à¤¾ à¤¬à¥à¤²à¥‰à¤—"
languageName = "à¤¹à¤¿à¤¨à¥à¤¦à¥€ ğŸ‡®ğŸ‡³"
languageCode = "hi"
contentDir = "content"
weight = 10

[hi.params]
description = "à¤¹à¤¾à¤°à¥à¤ªà¤° à¤°à¥€à¤¡ à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤²à¤¿à¤–à¥‡ à¤—à¤ à¤•à¥à¤› à¤²à¥‡à¤–à¥¤ à¤®à¥à¤–à¥à¤¯ à¤°à¥‚à¤ª à¤¸à¥‡ à¤¤à¤•à¤¨à¥€à¤•, à¤°à¤¾à¤œà¤¨à¥€à¤¤à¤¿ à¤”à¤° à¤…à¤¨à¥à¤¯ à¤µà¤¿à¤·à¤¯à¥‹à¤‚ à¤ªà¤°"
subtitle = "à¤à¤• à¤¸à¤¾à¤®à¤¾à¤¨à¥à¤¯ à¤µà¥à¤¯à¤•à¥à¤¤à¤¿ à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤¸à¤¾à¤®à¤¾à¤¨à¥à¤¯ à¤šà¥€à¤œà¥‡à¤‚ à¤•à¤°à¤¤à¥‡ à¤¹à¥à¤ à¤µà¤¿à¤šà¤¾à¤°"
