[en]
title = "Harper Reed's Blog"
languageName = "English ðŸ‡ºðŸ‡¸"
languageCode = "en-US"
contentDir = "content"
weight = 1

[en.params]
description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
subtitle = "Musing from a normal person doing normal things"

[es]
title = "Harper Reed's Blog"
languageName = "EspaÃ±ol ðŸ‡ªðŸ‡¸"
languageCode = "es"
contentDir = "content.es"
weight = 3


[es.params]
description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
subtitle = "Musing from a normal person doing normal things"


[ja]
title = "Harper Reed's Blog"
languageName = "æ—¥æœ¬èªž ðŸ‡¯ðŸ‡µ"
languageCode = "ja"
contentDir = "content"
weight = 2


[ja.params]
description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
subtitle = "Musing from a normal person doing normal things"


[ko]
title = "Harper Reed's Blog"
languageName = "í•œêµ­ì–´ ðŸ‡°ðŸ‡·"
languageCode = "ko"
contentDir = "content"
weight = 4


[ko.params]
description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
subtitle = "Musing from a normal person doing normal things"


[zh]
title = "Harper Reed's Blog"
languageName = "ä¸­æ–‡ ðŸ‡¨ðŸ‡³"
languageCode = "zh-CN"
contentDir = "content"
weight = 5

[zh.params]
description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
subtitle = "Musing from a normal person doing normal things"
