######### menu #########


[[main]]
identifier = "contact"
name = "harper@modest.com"
url = "mailto:harper@modest.com"
weight = 6

[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[footer]]
identifier = "home"
name = "Harper.lol"
url = "https://harper.lol"
weight = 5
