
ga_id = "UA-70650-74"

subtitle = "Musing from a normal person doing normal things"
cachebuster = "harper rules"
name = "Harper Reed"
email = "harper@modest.com"
# avatar = "https://s.gravatar.com/avatar/b7a96b3d5b5cfed5228396104cd67b38?s=600&r=g"
googleAnalytics = "UA-70650-74"

#Bear stuff
themeStyle = "france"
generateSocialCard = true



mainSections = [ "post" ]
images = ['https://harper.blog/images/og.png']


# [[social]]
# name = "harper.photos"
# icon = "fas fa-camera"
# url = "https://harper.photos"

# [[social]]
# name = "reading.lol"
# icon = "fas fa-book"
# url = "https://reading.lol"

# [[social]]
# name = "harperreed.com"
# icon = "fas fa-link"
# url = "http://harper.lol"
# twitter = 'harper'


[[params.plugins.js]]
link = "plugins/lazy-loader.js"
