# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Writing by Harper Reed
name: Harper Reed
email: harper+writing@nata2.org
description: > # this means to ignore newlines until "baseurl:"
  Some writing by Harper Reed. Mostly about technology, politics, and things.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://harper.blog" # the base hostname & protocol for your site
twitter_username: harper
github_username:  harperreed
instagram_username:  harperreed
google_analytics: UA-70650-74



permalink: pretty
markdown:    kramdown


kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

exclude:    ['CNAME','Makefile','Gemfile','Gemfile.lock','galleries.html',Makefile','s3_website.yml','_config.example.yml','s3_website.example.yml','README.md','.gitignore', 'node_modules']
